const ERROR_STATUS: Record<string, number> = {
  ERR_UNAUTHORIZED: 401,
  ERR_FORBIDDEN: 403,
  ERR_TREE_NAME_REQUIRED: 400,
  ERR_TREE_NAME_LENGTH: 400,
  ERR_FIRST_NAME_REQUIRED: 400,
  ERR_MEMBER_LIMIT_REACHED: 400,
  ERR_DEATH_BEFORE_BIRTH: 400,
  ERR_DUPLICATE_RELATIONSHIP: 409,
  ERR_SELF_RELATIONSHIP: 400,
};

export function statusForCode(code: string): number {
  return ERROR_STATUS[code] ?? 500;
}
